[project]
name = "thor"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "gmsh>=4.15.0",
    "jupyterlab>=4.5.3",
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "pandas>=3.0.0",
    "pyqt5>=5.15.11",
    "scipy>=1.17.0",
]
